//! Golden-file tests for `gpubox generate`: full-output comparisons (not
//! just substring checks) against a fixed hardware classification, so a
//! regression in rendering shows up as an exact diff against a known-good
//! snapshot instead of only failing on an unrelated substring assertion.
//! Deliberately drives the whole pipeline through `gpubox::launch::plan`
//! with `--gfx-override`, exactly the way the CLI does, rather than
//! hand-building a `LaunchSpec` - so these tests also catch regressions
//! introduced anywhere between probing and rendering.

use gpubox::generate::{self, Format};
use gpubox::launch::{self, Overrides};

fn plan_for(gfx_override: &str) -> gpubox::launch::Plan {
    let overrides = Overrides {
        gfx_override: Some(gfx_override.to_string()),
        // Pin the backend so these golden outputs are independent of both
        // the CI runner's platform and its invoking user:
        // - Without this, the *default* engine differs per platform
        //   (docker on Linux, windows-container on Windows for cuda/rocm/
        //   oneapi), and windows-container swaps `resolved.image` for
        //   `windows_image` - not what these Dockerfile-renderer tests are
        //   about.
        // - `mounts::plan` only injects HOME/USER/LOGNAME env vars for the
        //   docker/podman engines, keyed off the real invoking user (e.g.
        //   "runner" on a GitHub Actions runner) - "seatbelt" is engine-
        //   neutral for the Dockerfile-only assertions below, so it keeps
        //   this deterministic across hosts without pulling in code that's
        //   not actually what's being tested here.
        backend: Some("seatbelt".to_string()),
        ..Default::default()
    };
    launch::plan(&overrides, Vec::new(), true).expect("plan should resolve for a known override")
}

/// Golden Dockerfile for a plain, quirk-free NVIDIA card. Locks down the
/// exact `FROM`/`ENV`/prompt-marker shape `gpubox generate --format
/// dockerfile` produces.
#[test]
fn golden_dockerfile_for_nvidia_sm86() {
    let plan = plan_for("sm_86");
    let out = generate::render(Format::Dockerfile, &plan.resolved, &plan.spec).unwrap();
    let expected = "# Generated by `gpubox generate` for stack: cuda\n\
                    # Do not edit by hand - edit data/quirks.toml and regenerate instead.\n\
                    FROM nvidia/cuda:12.9.2-devel-ubuntu24.04\n\
                    \n\
                    ENV GPUBOX_STACK=cuda\n\
                    \n\
                    # Windows Container GPU passthrough (Engine::WindowsContainer) needs the \
                    CUDA toolkit installed into this base image yourself - the GPU driver \
                    itself comes from the host automatically and must not be baked in.\n\
                    \n\
                    # Prompt marker so you always know which gpubox stack you're in.\n\
                    RUN printf '%s\\n' 'export PS1=\"(gpubox:cuda) $PS1\"' > \
                    /etc/profile.d/gpubox-prompt.sh\n";
    assert_eq!(out, expected);
}

/// Golden Dockerfile for the Vulkan fallback, which - unlike a vendor
/// image - installs `packages` on top of a plain Ubuntu base.
#[test]
fn golden_dockerfile_for_vulkan_fallback() {
    let plan = plan_for("vulkan");
    let out = generate::render(Format::Dockerfile, &plan.resolved, &plan.spec).unwrap();
    let expected = "# Generated by `gpubox generate` for stack: vulkan\n\
                    # Do not edit by hand - edit data/quirks.toml and regenerate instead.\n\
                    FROM ubuntu:24.04\n\
                    \n\
                    RUN apt-get update && apt-get install -y --no-install-recommends \\\n    \
                    mesa-vulkan-drivers \\\n    vulkan-tools \\\n    libvulkan1 \\\n    \
                    && rm -rf /var/lib/apt/lists/*\n\
                    ENV GPUBOX_STACK=vulkan\n\
                    \n\
                    # No vendor-specific stack matched; using a plain Ubuntu base with Mesa's \
                    Vulkan drivers layered on top as the universal fallback. Run `gpubox \
                    generate --format dockerfile` to see (or customize) exactly what gets \
                    installed.\n\
                    \n\
                    # Prompt marker so you always know which gpubox stack you're in.\n\
                    RUN printf '%s\\n' 'export PS1=\"(gpubox:vulkan) $PS1\"' > \
                    /etc/profile.d/gpubox-prompt.sh\n";
    assert_eq!(out, expected);
}

/// Golden ROCm quirk Dockerfile: locks down that `HSA_OVERRIDE_GFX_VERSION`
/// actually lands as an `ENV` line for a card that needs it.
#[test]
fn golden_dockerfile_for_rocm_quirk_device() {
    let plan = plan_for("gfx90c");
    let out = generate::render(Format::Dockerfile, &plan.resolved, &plan.spec).unwrap();
    assert!(out.contains("FROM rocm/rocm-terminal:6.1"));
    assert!(out.contains("ENV HSA_OVERRIDE_GFX_VERSION=9.0.0"));
    assert!(out.contains("(gpubox:rocm)"));
}
