//! Seatbelt (`sandbox-exec`) backend for macOS.
//!
//! macOS has no Linux kernel to run OCI containers with GPU device nodes
//! passed through, so instead of containerizing, gpubox sandboxes the
//! target process directly on the host using Apple's Seatbelt sandbox
//! profile language (the same mechanism behind `sandbox-exec`, App
//! Sandbox, and much of macOS's own system hardening). The process still
//! runs as the invoking user against the host's own Metal stack - there is
//! no driver-matching problem on macOS the way there is with NVIDIA on
//! Linux, since the GPU stack is part of the OS itself.

use super::{Invocation, LaunchSpec};
use anyhow::Result;

/// Render a Seatbelt profile.
///
/// A strict default-deny profile (the "obvious" design) turns out to be
/// impractical here: GPU/Metal/WindowServer access alone requires dozens
/// of mach-lookup service names and IOKit user client classes that vary
/// across macOS versions, and getting even one wrong is an opaque abort
/// (SIGABRT) rather than a clean permission error. Since the goal is
/// filesystem scoping - keeping an arbitrary command from touching
/// anything outside the directories gpubox itself mounted through - not a
/// hardened multi-tenant sandbox, gpubox instead starts from `(allow
/// default)` and layers a `file-write*` deny over the whole filesystem,
/// re-allowing writes only under the mounted paths (home directory and
/// CWD). Reads are left unrestricted, matching distrobox's own model on
/// Linux where the container shares the host filesystem through bind
/// mounts rather than a read-restricted view.
pub fn render_profile(spec: &LaunchSpec) -> String {
    let mut allow_writes = String::new();
    for mount in &spec.mounts {
        if !mount.read_only {
            allow_writes.push_str(&format!(" (subpath \"{}\")", mount.host.display()));
        }
    }

    format!(
        "(version 1)\n\
         ;; Auto-generated by `gpubox generate` for stack: {stack}\n\
         ;; Broad default-allow scoped down to: writes are confined to the\n\
         ;; directories gpubox mounted through (home + CWD); everything else\n\
         ;; (including GPU/Metal access) behaves as it would unsandboxed.\n\
         (allow default)\n\
         (deny file-write* (subpath \"/\"))\n\
         (allow file-write*{allow_writes})\n",
        stack = spec.stack,
    )
}

pub fn build_invocation(spec: &LaunchSpec) -> Result<Invocation> {
    let profile = render_profile(spec);
    let profile_path = std::env::temp_dir().join(format!("gpubox-{}.sb", std::process::id()));

    let mut args = vec!["-f".to_string(), profile_path.display().to_string()];

    if spec.command.is_empty() {
        args.push(std::env::var("SHELL").unwrap_or_else(|_| "/bin/zsh".to_string()));
    } else {
        args.extend(spec.command.iter().cloned());
    }

    Ok(Invocation {
        program: "sandbox-exec".to_string(),
        args,
        generated_files: vec![(profile_path, profile)],
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mounts::BindMount;
    use std::path::PathBuf;

    fn sample_spec() -> LaunchSpec {
        LaunchSpec {
            image: "gpubox/metal:latest".to_string(),
            stack: "metal".to_string(),
            env: vec![],
            mounts: vec![BindMount {
                host: PathBuf::from("/Users/alice"),
                container: PathBuf::from("/Users/alice"),
                read_only: false,
            }],
            device_args: vec![],
            extra_args: vec![],
            packages: vec![],
            command: vec![],
            interactive: true,
            workdir: None,
        }
    }

    #[test]
    fn profile_scopes_writes_to_mounted_paths() {
        let profile = render_profile(&sample_spec());
        assert!(profile.contains("(allow default)"));
        assert!(profile.contains("(deny file-write* (subpath \"/\"))"));
        assert!(profile.contains("/Users/alice"));
    }

    #[test]
    fn profile_excludes_read_only_mounts_from_write_allowlist() {
        let mut spec = sample_spec();
        spec.mounts.push(BindMount {
            host: PathBuf::from("/opt/readonly-lib"),
            container: PathBuf::from("/opt/readonly-lib"),
            read_only: true,
        });
        let profile = render_profile(&spec);
        assert!(profile.contains("/Users/alice"));
        assert!(!profile.contains("/opt/readonly-lib"));
    }

    #[test]
    fn invocation_uses_sandbox_exec_with_profile_flag() {
        let inv = build_invocation(&sample_spec()).unwrap();
        assert_eq!(inv.program, "sandbox-exec");
        assert_eq!(inv.args[0], "-f");
        assert_eq!(inv.generated_files.len(), 1);
    }
}
