//! Windows Sandbox backend.
//!
//! Windows Sandbox is a disposable, Hyper-V-backed lightweight desktop VM
//! that ships with Windows 10/11 Pro+ - and, since 2020, supports opt-in
//! virtualized GPU acceleration (`<VGpu>Enable</VGpu>`). It's the most
//! GPU-friendly first-party Windows sandboxing technology that isn't
//! itself a Linux VM (ruling out WSL2), which is why gpubox uses it here
//! instead of trying to reimplement container semantics on top of Windows
//! Containers (which have no GPU story for non-DirectX-server workloads).
//!
//! Windows Sandbox always boots a clean copy of Windows, so there's no
//! "image" to select the way there is on Linux - `spec.image` is only
//! used as a label written into the generated config's comments and the
//! logon script, so `gpubox doctor` / `gpubox generate` output stays
//! consistent across platforms.

use super::{Invocation, LaunchSpec};
use anyhow::Result;

/// Render a `.wsb` (Windows Sandbox configuration) XML document.
pub fn render_config(spec: &LaunchSpec) -> String {
    let mut mapped_folders = String::new();
    for mount in &spec.mounts {
        let read_only = if mount.read_only { "true" } else { "false" };
        mapped_folders.push_str(&format!(
            "    <MappedFolder>\n      \
             <HostFolder>{host}</HostFolder>\n      \
             <SandboxFolder>{container}</SandboxFolder>\n      \
             <ReadOnly>{read_only}</ReadOnly>\n    \
             </MappedFolder>\n",
            host = mount.host.display(),
            container = mount.container.display(),
        ));
    }

    let logon_command = if spec.command.is_empty() {
        "cmd.exe".to_string()
    } else {
        spec.command.join(" ")
    };

    format!(
        "<!-- Auto-generated by `gpubox generate` for stack: {stack} (image label: {image}) -->\n\
         <Configuration>\n  \
         <VGpu>Enable</VGpu>\n  \
         <Networking>Enable</Networking>\n  \
         <MappedFolders>\n{mapped_folders}  </MappedFolders>\n  \
         <LogonCommand>\n    <Command>{logon_command}</Command>\n  </LogonCommand>\n\
         </Configuration>\n",
        stack = spec.stack,
        image = spec.image,
    )
}

pub fn build_invocation(spec: &LaunchSpec) -> Result<Invocation> {
    let config = render_config(spec);
    let config_path = std::env::temp_dir().join(format!("gpubox-{}.wsb", std::process::id()));

    Ok(Invocation {
        program: "WindowsSandbox.exe".to_string(),
        args: vec![config_path.display().to_string()],
        generated_files: vec![(config_path, config)],
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mounts::BindMount;
    use std::path::PathBuf;

    fn sample_spec() -> LaunchSpec {
        LaunchSpec {
            image: "gpubox/cuda:12.4".to_string(),
            stack: "cuda".to_string(),
            env: vec![],
            mounts: vec![BindMount {
                host: PathBuf::from(r"C:\Users\alice"),
                container: PathBuf::from(r"C:\Users\alice"),
                read_only: false,
            }],
            device_args: vec![],
            extra_args: vec![],
            packages: vec![],
            command: vec![],
            interactive: true,
            workdir: None,
        }
    }

    #[test]
    fn config_enables_vgpu() {
        let config = render_config(&sample_spec());
        assert!(config.contains("<VGpu>Enable</VGpu>"));
    }

    #[test]
    fn config_includes_mapped_folder() {
        let config = render_config(&sample_spec());
        assert!(config.contains(r"C:\Users\alice"));
    }

    #[test]
    fn invocation_targets_windows_sandbox_exe() {
        let inv = build_invocation(&sample_spec()).unwrap();
        assert_eq!(inv.program, "WindowsSandbox.exe");
        assert_eq!(inv.generated_files.len(), 1);
        assert!(inv.args[0].ends_with(".wsb"));
    }
}
