//! `gpubox generate`: emit the equivalent Dockerfile / Compose file /
//! Podman Quadlet / Seatbelt profile / `.wsb` config for a resolved
//! launch, so the "magic" of hardware detection + stack resolution is
//! inspectable, diffable, and reproducible outside of gpubox itself (e.g.
//! checked into a repo and used straight from CI).

use crate::backend::{self, Engine, Invocation, LaunchSpec};
use crate::stack::ResolvedStack;
use anyhow::{bail, Result};
use std::fmt::Write as _;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    Dockerfile,
    Compose,
    Quadlet,
    Seatbelt,
    WindowsSandbox,
    /// VS Code / GitHub Codespaces `.devcontainer/devcontainer.json`, so
    /// the same auto-detected image/mounts/device args slot directly into
    /// a Dev Containers workflow instead of only `docker run`/Compose.
    Devcontainer,
}

impl Format {
    pub fn parse(s: &str) -> Option<Format> {
        match s.to_ascii_lowercase().as_str() {
            "dockerfile" => Some(Format::Dockerfile),
            "compose" | "docker-compose" => Some(Format::Compose),
            "quadlet" => Some(Format::Quadlet),
            "seatbelt" | "sb" => Some(Format::Seatbelt),
            "wsb" | "windows-sandbox" => Some(Format::WindowsSandbox),
            "devcontainer" | "devcontainer.json" => Some(Format::Devcontainer),
            _ => None,
        }
    }

    pub fn default_for_platform() -> Format {
        if cfg!(target_os = "macos") {
            Format::Seatbelt
        } else if cfg!(target_os = "windows") {
            Format::WindowsSandbox
        } else {
            Format::Compose
        }
    }

    pub fn default_filename(self) -> &'static str {
        match self {
            Format::Dockerfile => "Dockerfile",
            Format::Compose => "compose.yaml",
            Format::Quadlet => "gpubox.container",
            Format::Seatbelt => "gpubox.sb",
            Format::WindowsSandbox => "gpubox.wsb",
            Format::Devcontainer => ".devcontainer/devcontainer.json",
        }
    }
}

fn shell_quote(arg: &str) -> String {
    if arg
        .chars()
        .all(|c| c.is_alphanumeric() || "-_./:=@".contains(c))
    {
        arg.to_string()
    } else {
        format!("'{}'", arg.replace('\'', "'\\''"))
    }
}

fn render_raw_command_comment(inv: &Invocation) -> String {
    let mut line = format!("# Equivalent to: {}", inv.program);
    for arg in &inv.args {
        let _ = write!(line, " {}", shell_quote(arg));
    }
    line
}

fn render_dockerfile(resolved: &ResolvedStack, spec: &LaunchSpec) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# Generated by `gpubox generate` for stack: {}",
        resolved.stack
    );
    let _ = writeln!(
        out,
        "# Do not edit by hand - edit data/quirks.toml and regenerate instead."
    );
    let _ = writeln!(out, "FROM {}", spec.image);
    out.push('\n');
    if !resolved.packages.is_empty() {
        let _ = writeln!(
            out,
            "RUN apt-get update && apt-get install -y --no-install-recommends \\\n    {} \\\n    && rm -rf /var/lib/apt/lists/*",
            resolved.packages.join(" \\\n    ")
        );
    }
    for (key, value) in &spec.env {
        let _ = writeln!(out, "ENV {key}={value}");
    }
    if let Some(notes) = &resolved.notes {
        out.push('\n');
        for line in notes.trim().lines() {
            let _ = writeln!(out, "# {line}");
        }
    }
    out.push('\n');
    out.push_str(
        "# Prompt marker so you always know which gpubox stack you're in.\n\
         RUN printf '%s\\n' 'export PS1=\"(gpubox:",
    );
    out.push_str(&resolved.stack);
    out.push_str(") $PS1\"' > /etc/profile.d/gpubox-prompt.sh\n");
    out
}

fn render_compose(inv: &Invocation, spec: &LaunchSpec) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# Generated by `gpubox generate` for stack: {}",
        spec.stack
    );
    let _ = writeln!(out, "{}", render_raw_command_comment(inv));
    out.push_str("services:\n  gpubox:\n");
    let _ = writeln!(out, "    image: {}", spec.image);
    out.push_str("    stdin_open: true\n    tty: true\n");
    if let Some(workdir) = &spec.workdir {
        let _ = writeln!(out, "    working_dir: {}", workdir.display());
    }
    if !spec.env.is_empty() {
        out.push_str("    environment:\n");
        for (key, value) in &spec.env {
            let _ = writeln!(out, "      {key}: \"{value}\"");
        }
    }
    if !spec.mounts.is_empty() {
        out.push_str("    volumes:\n");
        for mount in &spec.mounts {
            let ro = if mount.read_only { ":ro" } else { "" };
            let _ = writeln!(
                out,
                "      - {}:{}{}",
                mount.host.display(),
                mount.container.display(),
                ro
            );
        }
    }
    let device_paths: Vec<&str> = spec
        .device_args
        .windows(2)
        .filter(|w| w[0] == "--device" && w[1].starts_with('/'))
        .map(|w| w[1].as_str())
        .collect();
    if !device_paths.is_empty() {
        out.push_str("    devices:\n");
        for path in device_paths {
            let _ = writeln!(out, "      - {path}:{path}");
        }
    }
    let leftover: Vec<&String> = spec
        .device_args
        .iter()
        .filter(|a| a.as_str() != "--device" && !a.starts_with('/'))
        .chain(spec.extra_args.iter())
        .collect();
    if !leftover.is_empty() {
        out.push_str(
            "    # Compose has no direct equivalent for the following engine flags; \
             they're applied when gpubox runs the container directly, and are listed \
             here for visibility:\n",
        );
        for arg in leftover {
            let _ = writeln!(out, "    #   {arg}");
        }
    }
    out
}

/// Render a `.devcontainer/devcontainer.json` for VS Code / GitHub
/// Codespaces' Dev Containers extension, so gpubox's auto-detected
/// image/mounts/device flags slot straight into that workflow.
/// `runArgs` is where device injection and any other raw engine flags
/// land - devcontainer.json has no structured equivalent for `--gpus`/
/// `--device`, but happily passes arbitrary extra `docker run` flags
/// through via `runArgs`, so nothing is lost the way it would be with
/// Compose's device list (which can't express `--gpus all`, only device
/// paths).
fn render_devcontainer(resolved: &ResolvedStack, spec: &LaunchSpec) -> Result<String> {
    let mounts: Vec<String> = spec
        .mounts
        .iter()
        .map(|mount| {
            let mut s = format!(
                "source={},target={},type=bind",
                mount.host.display(),
                mount.container.display()
            );
            if mount.read_only {
                s.push_str(",readonly");
            }
            s
        })
        .collect();

    let run_args: Vec<String> = spec
        .device_args
        .iter()
        .chain(spec.extra_args.iter())
        .cloned()
        .collect();

    let container_env: serde_json::Map<String, serde_json::Value> = spec
        .env
        .iter()
        .map(|(k, v)| (k.clone(), serde_json::Value::String(v.clone())))
        .collect();

    let mut doc = serde_json::json!({
        "$schema": "https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json",
        "name": format!("gpubox ({})", resolved.stack),
        "image": spec.image,
        "mounts": mounts,
        "containerEnv": container_env,
        "runArgs": run_args,
    });
    if let Some(workdir) = &spec.workdir {
        doc["workspaceFolder"] = serde_json::Value::String(workdir.display().to_string());
    }

    let mut out = format!(
        "// Generated by `gpubox generate` for stack: {}\n",
        resolved.stack
    );
    out.push_str(&serde_json::to_string_pretty(&doc)?);
    out.push('\n');
    Ok(out)
}

fn render_quadlet(spec: &LaunchSpec) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# Generated by `gpubox generate` for stack: {}",
        spec.stack
    );
    out.push_str("[Unit]\n");
    let _ = writeln!(out, "Description=gpubox {} sandbox", spec.stack);
    out.push('\n');
    out.push_str("[Container]\n");
    let _ = writeln!(out, "Image={}", spec.image);
    // Use the exact same wrapper argv `enter`/`run` would exec inside the
    // container (passwd/group fixup, optional apt install, privilege
    // drop via setpriv - see backend::linux), shell-quoted, so the
    // generated unit is faithful to what gpubox actually does rather
    // than just the bare user command.
    let command_argv = backend::linux::command_argv(spec);
    let quoted_command = command_argv
        .iter()
        .map(|a| shell_quote(a))
        .collect::<Vec<_>>()
        .join(" ");
    let _ = writeln!(out, "Exec={quoted_command}");
    for mount in &spec.mounts {
        let ro = if mount.read_only { ",ro" } else { "" };
        let _ = writeln!(
            out,
            "Volume={}:{}{}",
            mount.host.display(),
            mount.container.display(),
            ro
        );
    }
    for (key, value) in &spec.env {
        let _ = writeln!(out, "Environment={key}={value}");
    }
    if let Some(workdir) = &spec.workdir {
        let _ = writeln!(out, "WorkingDir={}", workdir.display());
    }
    // Quadlet's PodmanArgs passes arbitrary flags straight through to
    // `podman run`, so - unlike Compose - device injection and any other
    // engine-specific flags translate losslessly.
    let podman_args: Vec<String> = spec
        .device_args
        .iter()
        .chain(spec.extra_args.iter())
        .cloned()
        .collect();
    if !podman_args.is_empty() {
        let _ = writeln!(out, "PodmanArgs={}", podman_args.join(" "));
    }
    out.push('\n');
    out.push_str("[Install]\nWantedBy=default.target\n");
    out
}

/// Render `spec` (with its resolved stack info) as the requested format.
/// Returns the file content plus the invocation it corresponds to (for
/// formats that need one, i.e. Compose/Quadlet, to embed the raw
/// command-for-reference comment).
pub fn render(format: Format, resolved: &ResolvedStack, spec: &LaunchSpec) -> Result<String> {
    match format {
        Format::Dockerfile => Ok(render_dockerfile(resolved, spec)),
        Format::Compose => {
            let inv = backend::build_invocation(Engine::Docker, spec)?;
            Ok(render_compose(&inv, spec))
        }
        Format::Quadlet => Ok(render_quadlet(spec)),
        Format::Seatbelt => Ok(backend::macos::render_profile(spec)),
        Format::WindowsSandbox => Ok(backend::windows::render_config(spec)),
        Format::Devcontainer => render_devcontainer(resolved, spec),
    }
}

/// Guard against nonsensical combinations, e.g. asking for a Seatbelt
/// profile on Linux CI where nothing will ever read it usefully - we still
/// allow it (that's the whole point of `generate` being inspectable
/// cross-platform) but this is where we'd add stricter checks later.
pub fn validate_format_for_stack(format: Format, resolved: &ResolvedStack) -> Result<()> {
    if format == Format::Seatbelt && resolved.stack == "cuda" {
        bail!("Seatbelt sandboxing has no device-injection story for NVIDIA/CUDA; pick a Linux backend for this stack instead");
    }
    let is_linux_format = matches!(
        format,
        Format::Dockerfile | Format::Compose | Format::Quadlet | Format::Devcontainer
    );
    if is_linux_format && resolved.stack == "metal" {
        bail!(
            "the `metal` stack runs natively via Seatbelt on macOS and has no container \
             image to put in a Dockerfile/Compose file/Quadlet unit; use `--format seatbelt` \
             instead"
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mounts::BindMount;
    use std::path::PathBuf;

    fn resolved() -> ResolvedStack {
        ResolvedStack {
            detected: "AMD (gfx90c)".to_string(),
            stack: "rocm".to_string(),
            image: "rocm/rocm-terminal:6.1".to_string(),
            env: [("HSA_OVERRIDE_GFX_VERSION".to_string(), "9.0.0".to_string())]
                .into_iter()
                .collect(),
            notes: Some("gfx90c needs the override quirk.".to_string()),
            packages: Vec::new(),
            rule_key: "amd.gfx90c".to_string(),
            windows_image: None,
        }
    }

    fn spec() -> LaunchSpec {
        LaunchSpec {
            image: "rocm/rocm-terminal:6.1".to_string(),
            stack: "rocm".to_string(),
            env: vec![("HSA_OVERRIDE_GFX_VERSION".to_string(), "9.0.0".to_string())],
            mounts: vec![BindMount {
                host: PathBuf::from("/home/alice"),
                container: PathBuf::from("/home/alice"),
                read_only: false,
            }],
            device_args: vec!["--device".to_string(), "/dev/dri".to_string()],
            extra_args: vec!["--group-add".to_string(), "keep-groups".to_string()],
            packages: vec![],
            command: vec![],
            interactive: true,
            workdir: Some(PathBuf::from("/home/alice/project")),
        }
    }

    #[test]
    fn dockerfile_includes_from_and_env() {
        let out = render(Format::Dockerfile, &resolved(), &spec()).unwrap();
        assert!(out.contains("FROM rocm/rocm-terminal:6.1"));
        assert!(out.contains("ENV HSA_OVERRIDE_GFX_VERSION=9.0.0"));
        assert!(out.contains("gpubox-prompt.sh"));
    }

    #[test]
    fn dockerfile_installs_packages_for_fallback_stacks() {
        let mut vulkan_resolved = resolved();
        vulkan_resolved.stack = "vulkan".to_string();
        vulkan_resolved.image = "ubuntu:24.04".to_string();
        vulkan_resolved.packages = vec![
            "mesa-vulkan-drivers".to_string(),
            "vulkan-tools".to_string(),
        ];
        let mut vulkan_spec = spec();
        vulkan_spec.image = "ubuntu:24.04".to_string();

        let out = render(Format::Dockerfile, &vulkan_resolved, &vulkan_spec).unwrap();
        assert!(out.contains("FROM ubuntu:24.04"));
        assert!(out.contains("apt-get install -y --no-install-recommends"));
        assert!(out.contains("mesa-vulkan-drivers"));
        assert!(out.contains("vulkan-tools"));
    }

    #[test]
    fn compose_includes_volumes_and_devices() {
        let out = render(Format::Compose, &resolved(), &spec()).unwrap();
        assert!(out.contains("image: rocm/rocm-terminal:6.1"));
        assert!(out.contains("/home/alice:/home/alice"));
        assert!(out.contains("/dev/dri:/dev/dri"));
        assert!(out.contains("# Equivalent to: docker run"));
    }

    #[test]
    fn quadlet_passes_device_args_through_podman_args_losslessly() {
        let out = render(Format::Quadlet, &resolved(), &spec()).unwrap();
        assert!(out.contains("Image=rocm/rocm-terminal:6.1"));
        assert!(out.contains("PodmanArgs=--device /dev/dri --group-add keep-groups"));
        assert!(out.contains("WorkingDir=/home/alice/project"));
    }

    #[test]
    fn seatbelt_rejects_cuda_stack() {
        let err = validate_format_for_stack(Format::Seatbelt, &resolved());
        assert!(err.is_ok()); // rocm is fine
        let mut cuda = resolved();
        cuda.stack = "cuda".to_string();
        assert!(validate_format_for_stack(Format::Seatbelt, &cuda).is_err());
    }

    #[test]
    fn linux_formats_reject_metal_stack() {
        let mut metal = resolved();
        metal.stack = "metal".to_string();
        for format in [Format::Dockerfile, Format::Compose, Format::Quadlet] {
            assert!(validate_format_for_stack(format, &metal).is_err());
        }
        // Seatbelt is exactly the right format for the metal stack.
        assert!(validate_format_for_stack(Format::Seatbelt, &metal).is_ok());
    }

    #[test]
    fn format_parsing_roundtrips_default_filenames() {
        for format in [
            Format::Dockerfile,
            Format::Compose,
            Format::Quadlet,
            Format::Seatbelt,
            Format::WindowsSandbox,
            Format::Devcontainer,
        ] {
            let name = format.default_filename();
            assert!(!name.is_empty());
        }
        assert_eq!(Format::parse("dockerfile"), Some(Format::Dockerfile));
        assert_eq!(Format::parse("wsb"), Some(Format::WindowsSandbox));
        assert_eq!(Format::parse("devcontainer"), Some(Format::Devcontainer));
        assert_eq!(Format::parse("nope"), None);
    }

    #[test]
    fn devcontainer_json_is_valid_json_with_expected_fields() {
        let out = render(Format::Devcontainer, &resolved(), &spec()).unwrap();
        // Strip the leading `//` comment line before parsing as JSON.
        let json_body = out.split_once('\n').unwrap().1;
        let value: serde_json::Value = serde_json::from_str(json_body).unwrap();
        assert_eq!(value["image"], "rocm/rocm-terminal:6.1");
        assert_eq!(value["containerEnv"]["HSA_OVERRIDE_GFX_VERSION"], "9.0.0");
        assert_eq!(value["workspaceFolder"], "/home/alice/project");
        let mounts = value["mounts"].as_array().unwrap();
        assert!(mounts[0]
            .as_str()
            .unwrap()
            .contains("source=/home/alice,target=/home/alice"));
        let run_args = value["runArgs"].as_array().unwrap();
        assert!(run_args.iter().any(|a| a == "--device"));
        assert!(run_args.iter().any(|a| a == "keep-groups"));
    }

    #[test]
    fn devcontainer_rejects_metal_stack() {
        let mut metal = resolved();
        metal.stack = "metal".to_string();
        assert!(validate_format_for_stack(Format::Devcontainer, &metal).is_err());
    }
}
